version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: healthmate_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  web:
    build:
      context: .
    command: "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      # Django environment variables
      DEBUG: '1'
      DJANGO_ALLOWED_HOSTS: 'localhost 0.0.0.0'
      DATABASE_NAME: healthmate_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: root
      DATABASE_HOST: db
      DATABASE_PORT: 5432

volumes:
  postgres_data:
